#@ load("@ytt:data", "data")
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: #@ "kubeapps.community.tanzu.vmware.com." + data.values.version
spec:
  refName: "kubeapps.community.tanzu.vmware.com"
  version: #@ data.values.version
  releasedAt: #@ data.values.releasedAt
  #! TODO(minelson): add includedSoftware with application version from
  #! Chart.yaml once released in TCE kapp controller version.
  #! See https://github.com/vmware-tanzu/carvel-kapp-controller/issues/212
  #! includedSoftware:
  #! - displayName: Kubeapps
  #!   version: TODO
  valuesSchema:
    openAPIv3:
      properties: #@ data.values.properties
  template:
    spec:
      fetch:
      - imgpkgBundle:
          #! TODO(minelson): set imgpkgBundle with the sha *after* uploading the build?
          image: #@ data.values.registry_domain + "/" + data.values.registry_project + "/kubeapps:" + data.values.version
      template:
      - helmTemplate:
          path: config/kubeapps
      - kbld:
          paths:
          - "-"
          - .imgpkg/images.yml
          - kbld_config.yml
      deploy:
      - kapp: {}
